development:
  username: nixoid
  password: we98h4987h987h1987htt87h87h
  url: http://localhost:8332/
  donations: 12SW1w5mvp9ExwMbM9kMwTbN4D9e75KQDr
  
test:
  username: bitcoin-admin
  password: 5MLpeupM46
  url: http://localhost:8332/
  donations: 12SW1w5mvp9ExwMbM9kMwTbN4D9e75KQDr
