development:
  adapter: mysql2
  encoding: utf8
  database: tradebitcoin_online
  username: root
  password:

staging:
  adapter: mysql2
  encoding: utf8
  database: tradeonline
  username: tradeonline
  password: 92847hg987h987h

test:
  adapter: mysql2
  encoding: utf8
  database: tradebitcoin_online_test
  username: root
  password:
