development:
  adapter: mysql2
  encoding: utf8
  database: tradebitcoin_online
  username: root
  password:

test:
  adapter: mysql2
  encoding: utf8
  database: bitcoin-bank_test
  username: rails
  password: rails
