development:
  api_url: https://api.yubico.com/wsapi/verify
  api_id: 12493
  api_key: u1DvRU+5kYVuyW5xY40kWyAZ4Mg=

staging:
  api_url: https://api.yubico.com/wsapi/verify
  api_id: 12493
  api_key: u1DvRU+5kYVuyW5xY40kWyAZ4Mg=

test:
  api_url: https://api.yubico.com/wsapi/verify
  api_id: 12493
  api_key: u1DvRU+5kYVuyW5xY40kWyAZ4Mg=
